import React from "react";
import {Providers} from "@/app/providers";
import {Metadata} from "next";
import "./globals.css";
import NavbarHeader from "@/app/components/NavbarHeader";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" className="dark">
        <body>
        <Providers>
            <NavbarHeader/>
            {children}
        </Providers>
        </body>
        </html>
    );
}
